/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "FlexSensor_1_aliases.h"
#include "FlexSensor_1.h"
#include "SPIM_Audio.h"
#include "SPIM_Audio_PVT.h"
#include "MISO_1_aliases.h"
#include "MISO_1.h"
#include "DIN_aliases.h"
#include "DIN.h"
#include "CLK_aliases.h"
#include "CLK.h"
#include "CSLD_aliases.h"
#include "CSLD.h"
#include "AudioTimer.h"
#include "audiotimer_isr.h"
#include "emFile.h"
#include "SPIM_TFT.h"
#include "SPIM_TFT_PVT.h"
#include "MISO_TFT_aliases.h"
#include "MISO_TFT.h"
#include "MOSI_TFT_aliases.h"
#include "MOSI_TFT.h"
#include "SCLK_TFT_aliases.h"
#include "SCLK_TFT.h"
#include "SS_TFT_aliases.h"
#include "SS_TFT.h"
#include "LED_aliases.h"
#include "LED.h"
#include "RESET_aliases.h"
#include "RESET.h"
#include "DC_aliases.h"
#include "DC.h"
#include "Get_ADCs_Timer.h"
#include "get_adcs_isr.h"
#include "ADC_FlexSensor_L.h"
#include "FlexSensor_2_aliases.h"
#include "FlexSensor_2.h"
#include "ADC_FlexSensor_R.h"
#include "I2C_MASTER_L.h"
#include "I2C_MASTER_L_PVT.h"
#include "SCL_1_aliases.h"
#include "SCL_1.h"
#include "SDA_1_aliases.h"
#include "SDA_1.h"
#include "TimeStamp_Timer.h"
#include "timestamp_timer_isr.h"
#include "SPIM_Audio_IntClock.h"
#include "emFile_SPI0.h"
#include "emFile_SPI0_PVT.h"
#include "emFile_mosi0_aliases.h"
#include "emFile_mosi0.h"
#include "emFile_Clock_1.h"
#include "emFile_miso0_aliases.h"
#include "emFile_miso0.h"
#include "emFile_sclk0_aliases.h"
#include "emFile_sclk0.h"
#include "emFile_SPI0_CS_aliases.h"
#include "emFile_SPI0_CS.h"
#include "SPIM_TFT_IntClock.h"
#include "ADC_FlexSensor_L_IRQ.h"
#include "ADC_FlexSensor_L_theACLK.h"
#include "ADC_FlexSensor_L_Bypass_aliases.h"
#include "ADC_FlexSensor_L_Bypass.h"
#include "ADC_FlexSensor_R_AMux.h"
#include "ADC_FlexSensor_R_Ext_CP_Clk.h"
#include "ADC_FlexSensor_R_IRQ.h"
#include "ADC_FlexSensor_R_theACLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

